/**
 * Step 24A production environment contract.
 *
 * Every entry here was derived by reading the code that reads the variable,
 * not by reading documentation. `environment.test.ts` re-derives the set of
 * variable names from the repository on every run and fails when this contract
 * and the code disagree in either direction, so a new `process.env` read
 * cannot reach production without being classified first.
 *
 * This file records the expected *presence* of a variable and never its value.
 * There is no field a value could be written into, and `secrets.test.ts`
 * additionally refuses any plausible credential in the release artifacts.
 */

export type EnvClassification =
  /** The Admin workspace cannot serve a signed-in operator without it. */
  | "REQUIRED_FOR_ADMIN_CORE"
  /** One optional capability needs it; Admin core runs without it. */
  | "REQUIRED_FOR_OPTIONAL_FEATURE"
  /** A switch that turns a capability on. Never a credential. */
  | "FEATURE_GATE"
  /** Credential material for an external provider. */
  | "PROVIDER_SECRET"
  /** Configuration that is safe to read aloud. */
  | "NON_SECRET_CONFIGURATION"
  /** Read only by test or test-only code. Must never be set in production. */
  | "TEST_ONLY"
  /** Still read somewhere but no longer serving a purpose. */
  | "DEPRECATED_UNUSED"

/** Which deployment the variable is meant to exist in. */
export type EnvScope =
  | "PRODUCTION_AND_PREVIEW"
  | "PRODUCTION_ONLY"
  | "PREVIEW_AND_DEVELOPMENT_ONLY"
  /** Supplied by the platform; an operator never sets it. */
  | "PLATFORM_PROVIDED"
  | "LOCAL_DEVELOPMENT_ONLY"

/**
 * What production is expected to look like at Admin cutover, before any
 * capability activation. `ABSENT` is a real requirement rather than an
 * absence of one: static AWS credentials present in production deliberately
 * disable evidence storage, so setting them would be a regression.
 */
export type EnvExpectation = "PRESENT" | "ABSENT" | "OPTIONAL"

export type EnvApp = "marketing" | "admin" | "customer"

export type EnvVariable = {
  name: string
  /** Workspaces whose runtime reads it. */
  apps: EnvApp[]
  classification: EnvClassification
  secret: boolean
  scope: EnvScope
  /** Expected presence at Admin production cutover. Never a value. */
  atAdminCutover: EnvExpectation
  /** The capability or behaviour the variable controls. */
  controls: string
  /** What the code does when the variable is absent or unparseable. */
  whenAbsent: string
  /** True when Admin production access itself cannot proceed without it. */
  blocksAdminLaunch: boolean
  /** True when absence costs only the optional capability named in `controls`. */
  blocksOptionalCapabilityOnly: boolean
  /** Repository-relative files that read it. Checked against disk. */
  readBy: string[]
}

const supabaseCore = "The Supabase project every server-side query and the Admin OTP exchange run against."

export const environmentContract: readonly EnvVariable[] = [
  {
    name: "ADMIN_AUTH_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "PRESENT",
    controls: "Admin sign-in. Exactly \"true\" builds the auth config; anything else returns null and /login renders its unavailable state.",
    whenAbsent: "authConfig() is null, every Admin page redirects to /login and /login says sign-in is not available yet.",
    blocksAdminLaunch: true,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/auth/config.ts"],
  },
  {
    name: "ADMIN_ORIGIN",
    apps: ["admin"],
    classification: "REQUIRED_FOR_ADMIN_CORE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "PRESENT",
    controls: "The one origin Admin will accept a mutation from and the origin OTP links return to.",
    whenAbsent: "authConfig() is null, so Admin has no sign-in at all.",
    blocksAdminLaunch: true,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/auth/config.ts"],
  },
  {
    name: "SUPABASE_URL",
    apps: ["marketing", "admin", "customer"],
    classification: "REQUIRED_FOR_ADMIN_CORE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "PRESENT",
    controls: supabaseCore,
    whenAbsent: "authConfig() and customerBackendConfig() are null, so customer actions and the Customer Portal both stay closed. The marketing site falls back to its email-only intake path.",
    blocksAdminLaunch: true,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/auth/config.ts", "apps/customer/lib/config.ts", "lib/supabase/config.ts"],
  },
  {
    name: "SUPABASE_SECRET_KEY",
    apps: ["marketing", "admin", "customer"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "PRESENT",
    controls: "The service-role key. Every Admin RPC is service-role-only, so this is the key that reaches the database.",
    whenAbsent: "authConfig() and customerBackendConfig() are null, so no Admin, customer-action, or Customer Portal request can reach the database.",
    blocksAdminLaunch: true,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/auth/config.ts", "apps/customer/lib/config.ts", "lib/supabase/config.ts"],
  },
  {
    name: "SUPABASE_PUBLISHABLE_KEY",
    apps: ["admin", "customer"],
    classification: "REQUIRED_FOR_ADMIN_CORE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "PRESENT",
    controls: "The anon key used for the Supabase Auth OTP exchange on sign-in.",
    whenAbsent: "authConfig() and customerBackendConfig() are null, so no Admin or customer one-time code can be issued or verified.",
    blocksAdminLaunch: true,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/auth/config.ts", "apps/customer/lib/config.ts"],
  },
  {
    name: "CUSTOMER_AUTH_ENABLED",
    apps: ["customer"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "OPTIONAL",
    controls: "Customer action links. Exactly \"true\" plus customerBackendConfig() opens them. It does not open the Customer Portal.",
    whenAbsent: "customerConfig() is null, so no customer action link can be opened. The Customer Portal keeps its own gate. Admin is unaffected.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/customer/lib/config.ts"],
  },
  {
    name: "CUSTOMER_PORTAL_ENABLED",
    apps: ["customer"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "OPTIONAL",
    controls: "Customer Portal login. Exactly \"true\" plus customerBackendConfig() opens /login and the portal routes. It does not read CUSTOMER_AUTH_ENABLED.",
    whenAbsent: "Portal login, /portal and the portal auth routes stay closed. Existing customer action links keep using CUSTOMER_AUTH_ENABLED.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/customer/lib/portal/config.ts"],
  },
  {
    name: "CUSTOMER_ORIGIN",
    apps: ["admin", "customer", "marketing"],
    classification: "REQUIRED_FOR_OPTIONAL_FEATURE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "OPTIONAL",
    controls: "The origin customer action links and Customer Portal requests must match, and the return origin for payment sessions.",
    whenAbsent: "customerBackendConfig() is null, so customer actions and the Customer Portal both stay closed and no customer-facing link can be composed.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/auth/config.ts", "apps/customer/lib/config.ts", "lib/payments/config.ts"],
  },
  {
    name: "NODE_ENV",
    apps: ["marketing", "admin", "customer"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PLATFORM_PROVIDED",
    atAdminCutover: "PRESENT",
    controls: "Cookie naming and the secure flag: \"production\" selects __Host- prefixed cookies and Secure.",
    whenAbsent: "Next.js sets it. A non-production value would select the development cookie names, which is why the production smoke test checks the cookie name.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: [
      "apps/admin/lib/auth/config.ts",
      "apps/customer/lib/config.ts",
      "apps/customer/lib/portal/config.ts",
      "lib/cases/intake.ts",
      "lib/enquiries/intake.ts",
      "lib/enquiry-config.ts",
      "lib/enquiry-delivery.ts",
      "lib/monitoring/intake.ts",
    ],
  },
  {
    name: "VERCEL_ENV",
    apps: ["marketing", "admin", "customer"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PLATFORM_PROVIDED",
    atAdminCutover: "PRESENT",
    controls: "The environment half of every live gate. Outgoing mail, inbound mail, evidence storage, the job worker and marketing indexing all require exactly \"production\".",
    whenAbsent: "Every one of those capabilities stays off, which is the safe direction.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: [
      "apps/admin/lib/communications/gate.ts",
      "apps/admin/lib/conversations/gate.ts",
      "apps/admin/lib/evidence/config.ts",
      "apps/admin/lib/jobs/config.ts",
      "apps/customer/lib/case/config.ts",
      "lib/site-visibility.ts",
    ],
  },
  {
    name: "VERCEL_DEPLOYMENT_ID",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PLATFORM_PROVIDED",
    atAdminCutover: "PRESENT",
    controls: "Stamped on the worker heartbeat so a release record can name the build that ran a job.",
    whenAbsent: "The heartbeat records null. Nothing else changes.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/jobs/config.ts"],
  },

  {
    name: "CRON_SECRET",
    apps: ["admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "PRESENT",
    controls: "Authenticates the scheduler against /api/internal/jobs/run, compared in constant time. Must be at least 16 characters.",
    whenAbsent: "jobWorkerConfig() reports disabled and the cron entry point answers 503 rather than running work.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/jobs/config.ts"],
  },
  {
    name: "JOB_WORKER_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "The daily job worker. Also a prerequisite for outgoing and inbound mail, so it is the single switch that stops all scheduled provider effects.",
    whenAbsent: "The worker is disabled, no job is claimed, and both mail gates read false whatever else is set.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/communications/gate.ts", "apps/admin/lib/conversations/gate.ts", "apps/admin/lib/jobs/config.ts"],
  },
  {
    name: "JOB_PROVIDER_MODE",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Whether job handlers may call a real provider. \"production\" is honoured only on a Vercel production deployment; \"mock\" is refused there.",
    whenAbsent: "Provider mode is \"disabled\" and no handler performs an external effect.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/jobs/config.ts"],
  },
  {
    name: "JOB_WORKER_CADENCE_SECONDS",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "OPTIONAL",
    controls: "Expected interval between worker runs, used to judge heartbeat freshness and to cap live mail cadence at 300 seconds.",
    whenAbsent: "Falls back to 86400 seconds, matching the unchanged 0 4 * * * schedule.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/jobs/config.ts"],
  },

  {
    name: "AWS_REGION",
    apps: ["admin", "customer"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "PRESENT",
    controls: "The region holding the evidence and inbound-mail buckets.",
    whenAbsent: "Evidence and inbound storage config are null, so no upload can be presigned and no attachment fetched.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/conversations/gate.ts", "apps/admin/lib/evidence/config.ts", "apps/customer/lib/case/config.ts"],
  },
  {
    name: "AWS_EVIDENCE_BUCKET",
    apps: ["admin", "customer"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "PRESENT",
    controls: "The evidence bucket. Validated against the S3 bucket-name grammar before use.",
    whenAbsent: "Evidence storage config is null and the Admin evidence surface cannot presign an upload.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/evidence/config.ts", "apps/customer/lib/case/config.ts"],
  },
  {
    name: "AWS_EVIDENCE_ROLE_ARN",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "PRESENT",
    controls: "The role the Admin runtime assumes through Vercel OIDC to reach evidence objects. Validated against the IAM role ARN grammar.",
    whenAbsent: "Evidence storage config is null.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/evidence/config.ts"],
  },
  {
    name: "AWS_CUSTOMER_EVIDENCE_ROLE_ARN",
    apps: ["customer"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "OPTIONAL",
    controls: "The separate, narrower role the Customer app assumes for customer-side evidence upload.",
    whenAbsent: "Customer evidence upload config is null; Admin-side evidence is unaffected.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/customer/lib/case/config.ts"],
  },
  {
    name: "AWS_INBOUND_MAIL_BUCKET",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "The bucket inbound mail attachments land in.",
    whenAbsent: "Inbound storage config is null, so an inbound attachment cannot be fetched.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/conversations/gate.ts"],
  },
  {
    name: "AWS_INBOUND_MAIL_ROLE_ARN",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "The role assumed to read inbound mail attachments.",
    whenAbsent: "Inbound storage config is null.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/conversations/gate.ts"],
  },
  {
    name: "AWS_ACCESS_KEY_ID",
    apps: ["admin", "customer"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "LOCAL_DEVELOPMENT_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Nothing, by design. Its presence makes every storage config return null so a long-lived key can never be used in production.",
    whenAbsent: "The intended state. Credentials come from Vercel OIDC role assumption instead.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/conversations/gate.ts", "apps/admin/lib/evidence/config.ts", "apps/customer/lib/case/config.ts"],
  },
  {
    name: "AWS_SECRET_ACCESS_KEY",
    apps: ["admin", "customer"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "LOCAL_DEVELOPMENT_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Nothing, by design. Presence disables storage exactly as AWS_ACCESS_KEY_ID does.",
    whenAbsent: "The intended state.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/conversations/gate.ts", "apps/admin/lib/evidence/config.ts", "apps/customer/lib/case/config.ts"],
  },
  {
    name: "AWS_SESSION_TOKEN",
    apps: ["admin", "customer"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "LOCAL_DEVELOPMENT_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Nothing, by design. Presence disables storage exactly as AWS_ACCESS_KEY_ID does.",
    whenAbsent: "The intended state.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: ["apps/admin/lib/conversations/gate.ts", "apps/admin/lib/evidence/config.ts", "apps/customer/lib/case/config.ts"],
  },

  {
    name: "COMMUNICATIONS_SEND_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Outgoing transactional mail from the Admin workspace. One of six conditions that must all hold.",
    whenAbsent: "communicationsSendEnabled() is false, the queue command refuses and the worker sends nothing.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/communications/gate.ts"],
  },
  {
    name: "COMMUNICATIONS_INBOUND_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Inbound mail ingestion. Independent of the outgoing gate; enabling one does not enable the other.",
    whenAbsent: "communicationsInboundEnabled() is false and the inbound webhook answers 503.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/conversations/gate.ts"],
  },
  {
    name: "COMMUNICATIONS_FROM_EMAIL",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "OPTIONAL",
    controls: "The sender address snapshotted onto a communication at review time and reused on every retry.",
    whenAbsent: "The outgoing gate reads false because it requires a parseable from-address.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/communications/gate.ts", "apps/admin/lib/communications/mail.ts", "apps/admin/lib/conversations/gate.ts"],
  },
  {
    name: "COMMUNICATIONS_LINK_SECRET",
    apps: ["admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "HMAC key for evidence-request capability links. At least 32 characters. Versioned siblings are read as COMMUNICATIONS_LINK_SECRET_V{n}.",
    whenAbsent: "linkSecret() is null, so an EVIDENCE_REQUEST communication cannot be drafted or sent.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/communications/link.ts"],
  },
  {
    name: "COMMUNICATIONS_LINK_KEY_VERSION",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "OPTIONAL",
    controls: "Which link-secret version new communications are stamped with. Stored on the row so rotation affects new messages only.",
    whenAbsent: "Falls back to version 1. An unparseable or out-of-range value also falls back to 1 rather than failing.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/communications/link.ts"],
  },
  {
    name: "RESEND_API_KEY",
    apps: ["marketing", "admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "OPTIONAL",
    controls: "Resend credential. Already present for marketing enquiry delivery; it is a condition of the Admin mail gates but on its own enables nothing in Admin.",
    whenAbsent: "Marketing enquiry config is not ready and both Admin mail gates read false.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: [
      "apps/admin/lib/communications/gate.ts",
      "apps/admin/lib/communications/mail.ts",
      "apps/admin/lib/conversations/attachment.ts",
      "apps/admin/lib/conversations/gate.ts",
      "apps/admin/lib/conversations/import.ts",
      "lib/enquiry-config.ts",
    ],
  },
  {
    name: "RESEND_WEBHOOK_SECRET",
    apps: ["admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Verifies outgoing-mail delivery webhooks from Resend.",
    whenAbsent: "The outgoing webhook rejects every request, so no delivery state is recorded.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/communications/webhook.ts"],
  },
  {
    name: "RESEND_INBOUND_WEBHOOK_SECRET",
    apps: ["admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Verifies inbound mail webhooks. At least 16 characters. Separate from the outgoing secret.",
    whenAbsent: "The inbound webhook rejects every request.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/conversations/gate.ts"],
  },
  {
    name: "INBOUND_MAIL_DOMAIN",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "The subdomain inbound mail is received on. The code refuses the apex profilerelaunch.com so inbound MX cannot be pointed at the root domain.",
    whenAbsent: "The inbound gate reads false.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/conversations/gate.ts"],
  },
  {
    name: "INBOUND_OWNED_ADDRESSES",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Addresses treated as our own when deciding the direction of an inbound message.",
    whenAbsent: "The owned-address list is empty; the inbound gate is already false without it.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/conversations/gate.ts"],
  },

  {
    name: "PAYMENTS_PROVIDER_MODE",
    apps: ["marketing", "admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Stripe. The only accepted value is \"stripe_test\"; there is no value that selects live Stripe.",
    whenAbsent: "Payment provider mode is \"disabled\" and no Stripe object can be created.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/payments/config.ts"],
  },
  {
    name: "STRIPE_SECRET_KEY",
    apps: ["marketing", "admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "The Stripe API key. Accepted only when it begins sk_test_ or rk_test_; a live key is rejected by the code.",
    whenAbsent: "No Stripe client is constructed.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/payments/config.ts", "lib/payments/stripe.ts"],
  },
  {
    name: "STRIPE_WEBHOOK_SECRET",
    apps: ["marketing", "admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Verifies Stripe webhook signatures. At least 16 characters.",
    whenAbsent: "The Stripe webhook rejects every request.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/payments/config.ts"],
  },

  {
    name: "GUARD_ACTIVATION_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Guard activation from a paid order.",
    whenAbsent: "Activation stays manual and direct billing stays PENDING.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/guard-billing/config.ts"],
  },
  {
    name: "GUARD_SUBSCRIPTIONS_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Guard subscription billing, which also depends on the Stripe gate.",
    whenAbsent: "No subscription is created or reconciled.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/guard-billing/config.ts"],
  },
  {
    name: "GUARD_REFUNDS_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Guard refunds, which move money and so also depend on the Stripe gate.",
    whenAbsent: "No refund can be issued.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/guard-billing/config.ts"],
  },
  {
    name: "GUARD_CHECKS_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Scheduled generation of Guard check obligations by the daily worker. Manual Guard checks do not depend on it.",
    whenAbsent: "No MAINTAIN_GUARD_CHECKS job or obligation is generated. An operator can still record a manual observation.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/guard-billing/config.ts"],
  },
  {
    name: "GUARD_ALERTS_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Automated Guard alert maintenance.",
    whenAbsent: "No alert is raised, escalated or closed automatically.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/guard-billing/config.ts"],
  },
  {
    name: "GUARD_ALERT_NOTIFICATIONS_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Outbound notification of a Guard alert, which also depends on the outgoing mail gate.",
    whenAbsent: "No Guard alert notification is composed or queued.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/guard-billing/config.ts"],
  },

  {
    name: "GOOGLE_BUSINESS_PROFILE_API_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "The Google Business Profile API gate. Setting it is still not sufficient: googleLiveStack is null in code.",
    whenAbsent: "The manual adapter resolves and the API is reported disabled.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/google-business-profile/config.ts"],
  },
  {
    name: "GOOGLE_BUSINESS_PROFILE_PROVIDER",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Which provider adapter is requested. Only a value in the production mode list is honoured; anything else, including \"mock\", falls back to manual.",
    whenAbsent: "Mode is \"manual\".",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/google-business-profile/config.ts"],
  },
  {
    name: "GOOGLE_BUSINESS_PROFILE_CLIENT_ID",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "OAuth client identifier for a future live Google connection.",
    whenAbsent: "googleOAuthConfig() is null and the configuration blocker oauth_not_configured is reported.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/google-business-profile/config.ts"],
  },
  {
    name: "GOOGLE_BUSINESS_PROFILE_CLIENT_SECRET",
    apps: ["admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "OAuth client secret for a future live Google connection.",
    whenAbsent: "googleOAuthConfig() is null.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/google-business-profile/config.ts"],
  },
  {
    name: "GOOGLE_BUSINESS_PROFILE_REDIRECT_URI",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "OAuth redirect target. Must begin https://.",
    whenAbsent: "googleOAuthConfig() is null.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/google-business-profile/config.ts"],
  },
  {
    name: "GOOGLE_BUSINESS_PROFILE_TOKEN_KEY",
    apps: ["admin"],
    classification: "PROVIDER_SECRET",
    secret: true,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "AES-256-GCM key for Google token storage. At least 32 characters. Never reaches the database or an RPC.",
    whenAbsent: "googleTokenEncryptionKey() is null and the blocker token_key_missing is reported.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/google-business-profile/config.ts"],
  },
  {
    name: "GOOGLE_BUSINESS_PROFILE_TOKEN_KEY_VERSION",
    apps: ["admin"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Which token key version new ciphertext is stamped with.",
    whenAbsent: "Falls back to \"v1\".",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/google-business-profile/config.ts"],
  },
  {
    name: "GOOGLE_LIVE_ACCEPTANCE_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "LOCAL_DEVELOPMENT_ONLY",
    atAdminCutover: "ABSENT",
    controls: "The live-provider acceptance harness, which would talk to the real Google API. Deliberately separate from the ordinary API gate.",
    whenAbsent: "The harness does not run.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/google-business-profile/config.ts"],
  },
  {
    name: "GOOGLE_SITE_VERIFICATION",
    apps: ["marketing"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "OPTIONAL",
    controls: "Search Console HTML-tag verification on the marketing site. Unrelated to the Business Profile API.",
    whenAbsent: "No verification meta tag is emitted.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/site-verification.ts"],
  },

  {
    name: "PRIVACY_DELETION_ENABLED",
    apps: ["admin"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Physical deletion of personal data during a privacy request.",
    whenAbsent: "Deletion performs nothing and the privacy page says so instead of offering an action that would not run.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["apps/admin/lib/settings/model.ts"],
  },

  {
    name: "CASE_PERSISTENCE_ENABLED",
    apps: ["marketing"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "PRESENT",
    controls: "Database-backed Get Help case intake on the marketing site. Admin's enquiry queue only receives work when this is on.",
    whenAbsent: "Intake stays on the email-only path and no row reaches the Admin queue.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/cases/persistence-config.ts"],
  },
  {
    name: "MONITORING_PERSISTENCE_ENABLED",
    apps: ["marketing"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "OPTIONAL",
    controls: "Database-backed /start-monitoring requests. A monitoring request is not paid Guard coverage.",
    whenAbsent: "The monitoring form reports itself temporarily unavailable.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/monitoring/persistence-config.ts"],
  },
  {
    name: "SITE_LAUNCHED",
    apps: ["marketing"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "OPTIONAL",
    controls: "Public search indexing of the marketing site, and only when VERCEL_ENV is production.",
    whenAbsent: "Pre-launch mode: noindex, robots.txt disallows everything, the sitemap is empty.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/site-visibility.ts"],
  },
  {
    name: "ENQUIRY_FROM_EMAIL",
    apps: ["marketing"],
    classification: "REQUIRED_FOR_OPTIONAL_FEATURE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "PRESENT",
    controls: "Sender of the marketing enquiry notification. Already live today.",
    whenAbsent: "Enquiry email config is not ready and the notification is not sent.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/enquiry-config.ts"],
  },
  {
    name: "ENQUIRY_TO_EMAIL",
    apps: ["marketing"],
    classification: "REQUIRED_FOR_OPTIONAL_FEATURE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "PRESENT",
    controls: "Recipient of the marketing enquiry notification. Already live today.",
    whenAbsent: "Enquiry email config is not ready.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: true,
    readBy: ["lib/enquiry-config.ts"],
  },
  {
    name: "ENQUIRY_REPLY_TO_EMAIL",
    apps: ["marketing"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "OPTIONAL",
    controls: "An extra Reply-To on the enquiry notification.",
    whenAbsent: "Only the customer's own address is used as Reply-To.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: ["lib/enquiry-config.ts"],
  },
  {
    name: "ENQUIRY_SEND_CUSTOMER_ACK",
    apps: ["marketing"],
    classification: "FEATURE_GATE",
    secret: false,
    scope: "PRODUCTION_AND_PREVIEW",
    atAdminCutover: "OPTIONAL",
    controls: "Whether the enquirer receives an acknowledgement email.",
    whenAbsent: "No acknowledgement is sent; internal delivery only.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: ["lib/enquiry-config.ts"],
  },
  {
    name: "NEXT_PUBLIC_GA_MEASUREMENT_ID",
    apps: ["marketing"],
    classification: "NON_SECRET_CONFIGURATION",
    secret: false,
    scope: "PRODUCTION_ONLY",
    atAdminCutover: "OPTIONAL",
    controls: "Google Analytics on the marketing site only, and only after explicit consent. Admin and Customer carry no analytics.",
    whenAbsent: "No analytics script is loaded and no consent banner is rendered.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: ["components/analytics-consent.tsx", "lib/analytics.ts"],
  },

  {
    name: "VITEST",
    apps: ["admin"],
    classification: "TEST_ONLY",
    secret: false,
    scope: "LOCAL_DEVELOPMENT_ONLY",
    atAdminCutover: "ABSENT",
    controls: "Nothing in production. The Google mock adapter throws unless it sees a test runtime, so this is a guard against the mock being reachable outside tests.",
    whenAbsent: "The intended state in every deployment.",
    blocksAdminLaunch: false,
    blocksOptionalCapabilityOnly: false,
    readBy: ["lib/google-business-profile/testing/mock-adapter.ts"],
  },
]

/**
 * Link secrets are read by a computed name when a rotation is in flight, so
 * the scanner cannot see them. The family is recorded here instead of being
 * silently missing from the contract.
 */
export const computedEnvFamilies = [
  {
    pattern: "COMMUNICATIONS_LINK_SECRET_V{n}",
    classification: "PROVIDER_SECRET" as EnvClassification,
    secret: true,
    controls:
      "A superseded evidence-link HMAC key, kept so communications stamped with an older version can still be re-derived on retry.",
    readBy: ["apps/admin/lib/communications/link.ts"],
  },
]

export function variable(name: string): EnvVariable | undefined {
  return environmentContract.find(entry => entry.name === name)
}

/** Variables without which a signed-in Admin cannot work at all. */
export function adminLaunchBlocking(): EnvVariable[] {
  return environmentContract.filter(entry => entry.blocksAdminLaunch)
}

/** Variables production is expected to be missing at Admin cutover. */
export function expectedAbsentAtCutover(): EnvVariable[] {
  return environmentContract.filter(entry => entry.atAdminCutover === "ABSENT")
}
