import { isUuid } from '../records/model'
import { validTime } from '../enquiries/model'
export const stages = { INITIAL_REVIEW:'Initial review', EVIDENCE_COLLECTION:'Collecting evidence', ASSESSMENT_READY:'Assessment ready', SERVICE_SELECTION:'Choosing the service', PAYMENT_REQUIRED:'Waiting for payment', AUTHORIZATION_REQUIRED:'Waiting for permission', PREPARATION:'Preparing the submission', READY_TO_SUBMIT:'Ready to submit', SUBMITTED:'Submitted', WAITING_GOOGLE:'Waiting for Google', OWNER_ACTION:'Customer action needed', FURTHER_REVIEW:'Further review', OUTCOME_REVIEW:'Reviewing the outcome', FINISHED:'Finished' } as const
export const tracks = { UNDECIDED:'Not selected', GUIDED:'Guided — customer submits', MANAGED:'Managed — ProfileRelaunch submits' } as const
export const outcomes = { RESTORED:'Restored',PARTIALLY_RESTORED:'Partially restored',NOT_RESTORED:'Not restored',REMOVED:'Removed',NOT_REMOVED:'Not removed',RESPONSE_RECOMMENDED:'Response recommended',WITHDRAWN:'Withdrawn' } as const
export type CaseRow = {id:string;reference:string;type:string;stage:keyof typeof stages;track:keyof typeof tracks;status:string;client:string;business:string;assigned:boolean;priority:string;nextAction:string;due:string|null;createdAt:string}
export type Task = {id:string;caseId:string;reference:string;title:string;owner:string;kind:string;due:string;source:string;timezone:string;status:string;resolution:string}
export type Submission = {id:string;actor:string;track:string;submittedAt:string;reference:string;channel:string;evidence:string;result:string|null;resultNote:string|null}
export type CaseDetail = CaseRow & {version:number;outcome:keyof typeof outcomes|null;summary:string;priorityReason:string;firstResponseDue:string|null;issue:string;reviewUrl:string|null;customerId:string;businessId:string;locationId:string;events:{id:string;event:string;note:string;visibility:string;createdAt:string;details:Record<string,unknown>}[];tasks:Task[];submissions:Submission[];transitions:(keyof typeof stages)[];customerPreview:{reference:string;type:string;summary:string;notes:string[]}}
export function filters(p:Record<string,string|string[]|undefined>,task=false){const {q='',filter=task?'open':'open',time,before}=p;const allowed=task?['open','overdue','customer','admin','resolved']:['open','all','closed','unassigned','overdue','GUIDED','MANAGED'];if(typeof q!=='string'||q.length>100||typeof filter!=='string'||!allowed.includes(filter)||(time===undefined)!==(before===undefined)||(time!==undefined&&!validTime(time))||(before!==undefined&&!isUuid(before)))return null;return {q:q.trim(),filter,time:time||null,before:before||null}}
