import Link from "next/link"
import { ArrowDownRight, ArrowUpRight, Check, ShieldCheck } from "lucide-react"
import { services, faqs } from "@/lib/content"
import { EnquiryForm } from "@/components/enquiry-form"

export function Hero(){return <section className="grid-lines overflow-hidden border-b border-[var(--line)]"><div className="container grid min-w-0 gap-14 py-16 md:grid-cols-[1.15fr_.85fr] md:items-end md:py-28"><div className="min-w-0"><p className="eyebrow break-words">Independent reputation support</p><h1 className="display mt-7 max-w-4xl break-words">Protect the trust you&apos;ve worked <span className="text-[var(--green)]">hard to earn.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[var(--muted)]">Practical, evidence-led support for Google Business Profile recovery and review issues. Clear next steps, grounded in the facts.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/get-help" className="group flex items-center gap-3 rounded-full bg-[var(--green)] px-6 py-4 font-bold text-white transition-transform hover:-translate-y-0.5">Tell us what happened <ArrowUpRight size={16} className="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></Link><Link href="/how-it-works" className="flex items-center gap-2 rounded-full border border-[var(--ink)] px-6 py-4 font-bold">How it works <ArrowDownRight size={16}/></Link></div></div><div className="relative min-h-72 overflow-hidden rounded-[2rem] bg-[var(--green)] p-8 text-white md:min-h-96 md:p-10"><div className="hero-panel-orbit absolute -right-14 -top-14 size-56 rounded-full border-[28px] border-[var(--lime)]/80"/><div className="hero-panel-orbit-bottom absolute -bottom-20 -left-12 size-56 rounded-full border-[28px] border-white/15"/><ShieldCheck className="relative text-[var(--lime)]" size={42}/><div className="relative mt-20 font-[var(--font-display)] text-4xl font-extrabold leading-[.95] tracking-[-.07em] md:text-5xl">Clarity<br/><span className="text-[var(--lime)]">before action.</span></div><p className="relative mt-7 max-w-xs text-sm leading-6 text-white/70">We turn a confusing platform or review issue into a documented, considered next step.</p></div></div></section>}
export function Services(){return <section className="bg-white py-24"><div className="container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Where we help</p><h2 className="section-title mt-5 max-w-2xl">Support for the moments that affect trust.</h2></div><p className="max-w-xs text-sm leading-6 text-[var(--muted)]">No inflated promises. Just focused support for a situation that deserves careful handling.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2">{services.map((s,i)=><Link key={s.href} href={s.href} className="group rounded-[1.75rem] border border-[var(--line)] p-8 transition hover:-translate-y-1 hover:border-[var(--green)] hover:shadow-[0_18px_50px_rgba(16,38,31,.08)]"><div className="flex items-start justify-between"><p className="text-sm font-bold text-[var(--green)]">0{i+1} / {s.kicker}</p><ArrowUpRight className="text-[var(--green)] transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" size={20}/></div><h3 className="mt-16 font-[var(--font-display)] text-3xl font-extrabold tracking-[-.06em]">{s.title}</h3><p className="mt-4 max-w-md leading-7 text-[var(--muted)]">{s.description}</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-bold">Explore service <ArrowUpRight size={15}/></span></Link>)}</div></div></section>}
export function Process(){return <section className="container py-24"><div className="grid gap-14 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">A simple process</p><h2 className="section-title mt-5">Good support starts with good information.</h2><p className="mt-7 max-w-sm leading-7 text-[var(--muted)]">You do not need to know the right platform language before you get in touch. Start with what you know.</p></div><div className="flex flex-col gap-2">{["Share the situation","Sort the evidence","Choose the next step"].map((x,i)=><div key={x} className="group flex gap-6 border-t border-[var(--line)] py-7"><div className="flex size-11 shrink-0 items-center justify-center rounded-full bg-[var(--lime)] font-black">0{i+1}</div><div><h3 className="font-[var(--font-display)] text-2xl font-extrabold tracking-[-.05em]">{x}</h3><p className="mt-2 leading-7 text-[var(--muted)]">We keep the process clear, proportionate and grounded in what can actually be supported.</p></div></div>)}</div></div></section>}
export function EnquirySection({caseMode=false}:{caseMode?:boolean}){return <section className="bg-[var(--warm)] py-24"><div className="container grid gap-12 md:grid-cols-[.8fr_1.2fr] md:items-start"><div><p className="eyebrow">{caseMode?"Start with the facts":"Let's talk"}</p><h2 className="section-title mt-5">{caseMode?"Tell us what happened.":"A clear first conversation."}</h2><p className="mt-7 max-w-sm leading-7 text-[var(--muted)]">{caseMode?"Share the details of your case and we&apos;ll help you understand what to do next.":"Have a question about our approach or a situation you are weighing up? Send a few details."}</p></div><EnquiryForm caseMode={caseMode}/></div></section>}
export function FAQ(){return <section className="bg-white py-24"><div className="container max-w-3xl"><p className="eyebrow">Useful to know</p><h2 className="section-title mt-5">Straight answers.</h2><div className="mt-12 flex flex-col gap-3">{faqs.map(f=><details key={f.q} className="group rounded-2xl border border-[var(--line)] p-6"><summary className="cursor-pointer list-none pr-8 font-bold marker:hidden">{f.q}</summary><p className="mt-4 leading-7 text-[var(--muted)]">{f.a}</p></details>)}</div></div></section>}
export function PageIntro({kicker,title,body}:{kicker:string;title:string;body:string}){return <section className="grid-lines border-b border-[var(--line)]"><div className="container py-20 md:py-28"><p className="eyebrow">{kicker}</p><h1 className="display mt-6 max-w-5xl">{title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[var(--muted)]">{body}</p></div></section>}
export function Bullets({items}:{items:string[]}){return <ul className="flex flex-col gap-4">{items.map(x=><li key={x} className="flex gap-3 leading-7"><Check className="mt-1 shrink-0 text-[var(--green)]" size={19}/>{x}</li>)}</ul>}
