import Link from "next/link"
import { ArrowUpRight, Check, ChevronDown } from "lucide-react"
import type { ResourceRecord } from "@/lib/resources"
import { suspensionBeforeAppealSources } from "@/lib/resource-articles/google-business-profile-suspended-before-appeal"
import { resourceArticleJsonLd, resourceBreadcrumbJsonLd } from "@/lib/resource-schema"
import { getResourceCategory } from "@/lib/resources"
import { ResourceBreadcrumbs } from "./resource-breadcrumbs"
import styles from "./resource-article.module.css"

const steps = [
  ["See what Google has restricted", "Save Google's reason and policy link."],
  ["Check that the business is eligible", "Make sure the business qualifies."],
  ["Compare the profile with the real business", "Check that the profile matches how the business actually operates."],
  ["Prepare the evidence", "Gather genuine records that support the case."],
  ["Submit when you are ready", "Use Google's official appeal process."],
]
const mistakes = [
  ["Appealing before checking the profile", "Submitting first and investigating afterwards can mean defending information that still needs correcting."],
  ["Guessing the suspension cause", "Treat Google's policy information as something to investigate. Don't claim to know the exact trigger unless you genuinely do."],
  ["Making several speculative edits", "Changing the name, address, category, hours and other fields at once makes it harder to distinguish genuine corrections from experimentation."],
  ["Using the wrong location setup", "A service-area business should not present itself as a customer-facing storefront if customers do not actually visit the address. Equally, don't hide a genuine storefront simply because you think it may help an appeal."],
  ["Starting the evidence search after the timer begins", "Prepare your files before opening the evidence form."],
  ["Uploading irrelevant documents", "More files do not automatically make a stronger case."],
  ["Creating a replacement profile", "Google specifically says not to create another Business Profile for the same business while the appeal is under review."],
  ["Sending another appeal while one is pending", "Google says not to submit multiple appeals for the same issue before receiving a decision."],
]
const scenarios = [
  ["I don't know why Google suspended my profile", "Start with what Google has actually provided. Open the appeals tool using the appropriate Google Account and save the moderation reason and policy link it shows. Review the profile against that policy area and Google's wider Business Profile guidelines. Don't tell Google that you know exactly what triggered the suspension if you don't. Build the appeal around facts you can establish rather than speculation about Google's internal systems."],
  ["I run a service-area business from home", "A home address does not automatically make the business ineligible. If customers do not come to the address to receive the service, Google's service-area guidance says the address should not be displayed publicly. The key question is how the business genuinely serves customers."],
  ["Several profiles I manage were suspended", "Check whether the issue may involve the Google Account rather than several unrelated profile problems. Google says an account restriction can suspend Business Profiles managed by that account and prevent the account from creating or claiming other profiles. Its guidance says the account restriction should be appealed and lifted before appealing the affected profile suspension."],
  ["I've already submitted my appeal", "Don't create a replacement profile or submit another appeal for the same issue while Google's first review is pending. Keep the evidence and submission record together and monitor the appeal status. If Google denies a reinstatement request, its current guidance says an additional review may be available. Review the denial and the evidence already submitted before deciding what genuinely new information could help."],
]

function ContextualCta({ heading, body, ctaLabel = "Start your Profile Recovery assessment" }: { heading: string; body: string; ctaLabel?: string }) {
  return <aside className={styles.pilotCta}><h2>{heading}</h2><p>{body}</p><Link className={styles.primaryAction} href="/get-help?service=profile-recovery">{ctaLabel}</Link><small>No fee to submit • Human-reviewed • No passwords or verification codes</small></aside>
}

export function SuspensionPilotView({ resource, related }: { resource: ResourceRecord; related: ResourceRecord[] }) {
  const category = getResourceCategory(resource.category)
  return <article className={`${styles.page} ${styles.pilotPage}`}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(resourceArticleJsonLd(resource)) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(resourceBreadcrumbJsonLd(resource, category.title)) }} />
    <ResourceBreadcrumbs resource={resource} />
    <header className={`${styles.hero} ${styles.wide}`}>
      <p className={styles.eyebrow}>Profile Recovery</p><h1>{resource.title}</h1>
      <div className={styles.intro}><p>If your Google Business Profile has been suspended, don&apos;t rush straight into the appeal. First check what Google has restricted, make sure the business and profile still meet Google&apos;s rules, and get your evidence ready.</p><p>If Google offers you the evidence form, the submission window is limited to 60 minutes. It is much easier to prepare the documents before you start than to search for them while the clock is running.</p></div>
      <p className={styles.pilotMeta}>Last reviewed 14 September 2026 · 10 min read</p>
    </header>
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>Before you appeal</h2><p>Work through these checks before you submit anything. If one step uncovers a problem, deal with that first rather than pushing ahead with an appeal you cannot properly support.</p><div className={styles.process}>{steps.map(([title, body], index) => <div className={styles.processStep} key={title}><b>{String(index + 1).padStart(2, "0")}</b><h3>{title}</h3><p>{body}</p></div>)}</div><div className={styles.warning}><strong>While an appeal is pending</strong><p>Don&apos;t create another Business Profile for the same business, and don&apos;t submit another appeal for the same issue while you are waiting for Google&apos;s decision.</p></div></section>
    <ContextualCta heading="Not sure which step is causing the problem?" body="You don't need to diagnose the whole suspension before asking for help. Tell us what Google has shown you and what you have already checked." />
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>Start with what Google has actually told you</h2><p>Open Google&apos;s appeals tool using the Google Account associated with the affected Business Profile. The tool can show the restricted profile, the reason for the moderation action and a link to the policy connected to it.</p><p>Save that information before making changes or writing an appeal. A policy area is a place to investigate; it does not necessarily tell you which individual field caused the suspension.</p><p>If Google has not identified a more specific cause, don&apos;t invent one.</p><div className={styles.compactCard}><h3>Save these for your case</h3><ul>{["the suspension or restriction email", "the wording shown in the appeals tool", "the affected Business Profile", "the moderation reason", "the policy link Google provides", "relevant dates"].map(item => <li key={item}>{item}</li>)}</ul></div></section>
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>Check that the business is eligible</h2><p>Before you appeal, make sure the business actually qualifies for a Google Business Profile. Google generally requires businesses to have in-person contact with customers, although there are exceptions. Online-only and lead-generation businesses are among those Google says are not eligible.</p><p>If you&apos;re unsure whether the business qualifies, resolve that first. Evidence won&apos;t fix an eligibility problem.</p><div className={styles.compactCard}><h3>Ask yourself</h3><ul>{["Does the business genuinely serve customers in person?", "Is it a storefront, service-area business or hybrid business?", "Is the business itself responsible for providing the service represented by the profile?", "Is the location genuinely connected to the business?"].map(item => <li key={item}>{item}</li>)}</ul></div><p>If any of those answers are uncertain, check the relevant Google rules before treating the case as a straightforward appeal.</p></section>
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>Does the profile match the real business?</h2><p>Next, compare the Business Profile with the business as it actually operates.</p><p>This isn&apos;t about making the listing look stronger for an appeal. It is about finding information that is inaccurate, outdated or difficult to support.</p><div className={styles.checkGrid}>{["Business name", "Address or service-area setup", "Phone number", "Website", "Primary category", "Additional categories where relevant", "Opening hours", "Owners and managers"].map(item => <span key={item}><Check size={16} aria-hidden="true" />{item}</span>)}</div><p>Correct genuine inaccuracies where appropriate, but avoid changing several fields simply because somebody online says a particular edit fixes suspensions. If you make a correction, it should be because the profile did not accurately represent the real business, not because you are experimenting with different configurations.</p></section>
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>Is the address set up correctly?</h2><p>Address setup deserves particular attention because Google treats storefront, service-area and hybrid businesses differently.</p><div className={styles.decisionGrid}>{[["Customers come to your location", "Storefront", "A customer-facing location may display its address when the business genuinely serves customers there and meets Google's location requirements."], ["You travel or deliver to customers", "Service-area business", "If customers do not come to your business address to receive the service, Google says the address should not be shown publicly. Use the appropriate service area instead."], ["Customers visit you and you also travel to them", "Hybrid business", "A hybrid business can serve customers at its location and also visit or deliver to customers."]].map(([lead, title, body]) => <div key={title}><p>{lead}</p><h3>{title}</h3><span>{body}</span></div>)}</div><p>Use the setup that reflects how the business really works. Don&apos;t hide a genuine storefront or create the appearance of a storefront simply to try to resolve a suspension.</p><Link className={styles.inlineLink} href="/resources/google-business-profile-address-and-service-area-rules">Read our full guide to Google Business Profile address and service-area rules →</Link></section>
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>Get your evidence ready before you start</h2><p>Google may offer an optional evidence form as part of the appeal process. Its current guidance gives examples of records that can strengthen an appeal.</p><p>You do not need every document on Google&apos;s list. Use genuine records that actually help establish the business or support information relevant to the profile.</p><div className={styles.evidenceGrid}>{[["Official business registration", "Can help establish the business and the details recorded by the relevant authority."], ["Business licence", "Can support the business or activity where a genuine licence applies."], ["Tax certificates", "Can help support business identity or other recorded business details."], ["Business utility bills", "Can help connect the business with relevant contact or location information."]].map(([title, body]) => <div key={title}><h3>{title}</h3><p>{body}</p></div>)}</div><p>Where documents contain the business name and address, Google advises checking that they match the profile being appealed. If something does not match, understand why before submitting the appeal. Do not alter genuine records simply to manufacture consistency.</p><div className={styles.timeWarning}><strong>60-minute evidence window</strong><p>If you open Google&apos;s linked evidence form, Google says the evidence must be submitted within 60 minutes or it will not be attached to the appeal.</p><b>Have the files ready first.</b></div><h3>Quality matters more than quantity</h3><p>Don&apos;t upload documents simply to create a larger evidence pack. Ask what each document actually proves and whether that fact is relevant to this profile and appeal.</p><div className={styles.questionGrid}>{["Does it establish the business?", "Does it support the location?", "Does it support information on the profile?", "Does it relate to this business and this appeal?"].map(item => <div key={item}>{item}</div>)}</div><p>Use evidence to establish facts, not to overwhelm the reviewer.</p><Link className={styles.inlineLink} href="/resources/google-business-profile-appeal-evidence-checklist">See the full Google Business Profile appeal evidence checklist →</Link></section>
    <ContextualCta heading="Have documents but aren't sure what actually helps your case?" body="We can review what Google has told you, the profile setup and the evidence you already have before you decide what to submit." ctaLabel="Get your case reviewed" />
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>Mistakes that can make the situation harder</h2><div className={styles.mistakeGrid}>{mistakes.map(([title, body]) => <div key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></section>
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>What if my situation is slightly different?</h2><div className={styles.accordion}>{scenarios.map(([title, body]) => <details key={title}><summary>{title}<ChevronDown size={18} aria-hidden="true" /></summary><p>{body}</p></details>)}</div></section>
    <section className={`${styles.pilotSection} ${styles.wide}`}><h2>What comes directly from Google</h2><p>The advice above combines Google&apos;s published rules with ProfileRelaunch&apos;s practical guidance. These are the main points that come directly from Google&apos;s current Business Profile Help pages:</p><ul className={styles.tickList}>{["Check that the profile follows Business Profile guidelines before appealing.", "The appeals tool can show the restricted profile, moderation reason and relevant policy link.", "Google may offer an optional evidence form.", "Examples of supporting evidence include business registration, licences, tax certificates and business utility bills.", "Google advises checking that the business name and address on supporting documents match the profile being appealed.", "Evidence submitted through the linked form must be submitted within Google's 60-minute window.", "Do not create another Business Profile for the same business while the appeal is being reviewed.", "Do not submit multiple appeals for the same issue before receiving a decision.", "If a reinstatement request is denied, an additional review may be available."].map(item => <li key={item}><Check size={18} aria-hidden="true" />{item}</li>)}</ul><div className={styles.practical}><strong>Our practical view</strong><p>Prepare first and appeal second. The strongest case is one where the business is eligible, the profile accurately reflects the real business, and the evidence supports the facts you are asking Google to accept.</p></div></section>
    <section className={`${styles.pilotConversion} ${styles.wide}`}><h2>Want someone to review the case before you appeal?</h2><p>You don&apos;t need to work out every part of the suspension on your own.</p><p>Tell us what happened, what Google has shown you and what you&apos;ve already checked. We&apos;ll review the situation and help you understand the appropriate next step.</p><div className={styles.pilotConversionActions}><Link className={styles.primaryAction} href="/get-help?service=profile-recovery">Start your Profile Recovery assessment</Link><Link className={styles.secondaryAction} href="/business-profile-recovery">See how Profile Recovery works</Link></div><small>No fee to submit • Human-reviewed • No passwords or verification codes</small></section>
    <section className={`${styles.related} ${styles.wide}`}><h2>Useful next guides</h2><div>{related.map(item => <Link className={styles.relatedPilotCard} key={item.slug} href={`/resources/${item.slug}`}><strong>{item.title}</strong><span>{item.slug.includes("evidence") ? "What to collect, what each document can help establish and how to prepare before Google's evidence window begins." : "What to check if Google does not approve the first appeal and when additional review may be available."}</span></Link>)}</div></section>
    <section className={`${styles.sourcesPilot} ${styles.wide}`}><h2>Official Google sources</h2><p>Google Business Profile Help</p><ul>{suspensionBeforeAppealSources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer">{source.title}<ArrowUpRight size={15} aria-hidden="true" /></a></li>)}</ul></section>
    <section className={`${styles.aboutPilot} ${styles.wide}`}><h2>About this guide</h2><p>This guide is based on Google&apos;s publicly available Business Profile guidance and was last reviewed on 14 September 2026. ProfileRelaunch is independent of Google.</p></section>
  </article>
}

export const suspensionPilotSlug = "google-business-profile-suspended-before-appeal"
